# Generated by Django 5.2.13 on 2026-06-23 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metrics_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dietary_restrictions', models.JSONField(blank=True, default=list)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FoodRestriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restriction_type', models.CharField(choices=[('CELIACO', 'Celíaco'), ('INTOLERANTE_A_LACTOSE', 'Intolerante à Lactose'), ('DIABETICO', 'Diabético'), ('ALERGICO_OVO', 'Alérgico a ovo'), ('FRUTOS_DO_MAR', 'Alérgico a frutos do mar'), ('AMENDOIM', 'Alérgico a amendoim'), ('SOJA', 'Alérgico à soja'), ('AVEIA', 'Alérgico à aveia'), ('OUTRO', 'Outro')], max_length=30)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restriction_items', to='profiles.nutritionalprofile')),
            ],
        ),
        migrations.CreateModel(
            name='SavedDiet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Plano Alimentar Inteligente', max_length=255)),
                ('content', models.TextField(help_text='Conteúdo em Markdown gerado pela IA')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_diets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SavedRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Receita Saudável', max_length=255)),
                ('content', models.TextField(help_text='Conteúdo em Markdown gerado pela IA')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_recipes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Meu Plano Semanal', max_length=255)),
                ('is_active', models.BooleanField(default=False, help_text='É o plano que o usuário está seguindo agora?')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('target_kcal_per_day', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('plan_data', models.JSONField(help_text='JSON estruturado contendo os dias, refeições e ingredientes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_plans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
