# Generated by Django 5.2.12 on 2026-04-07 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('height_cm', models.PositiveIntegerField()),
                ('age', models.PositiveIntegerField()),
                ('sex', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('activity_level', models.CharField(choices=[('SEDENTARIO', 'Sedentário'), ('LEVE', 'Leve'), ('MODERADA', 'Moderada'), ('ALTA', 'Alta'), ('MUITO_ALTA', 'Muito Alta')], max_length=15)),
                ('goal', models.CharField(choices=[('PERDA', 'Perda'), ('MANUTENCAO', 'Manuteção'), ('GANHO', 'Ganho')], max_length=15)),
                ('bmr', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('daily_calorie_target', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nutritional_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
