# Generated by Django 5.2.13 on 2026-07-02 04:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nutritionalprofile',
            name='metrics_data',
        ),
        migrations.AddField(
            model_name='nutritionalprofile',
            name='activity_level',
            field=models.CharField(choices=[('SEDENTARIO', 'Sedentário'), ('LEVE', 'Leve'), ('MODERADA', 'Moderada'), ('ALTA', 'Alta'), ('MUITO_ALTA', 'Muito Alta')], default='SEDENTARIO', max_length=15),
        ),
        migrations.AddField(
            model_name='nutritionalprofile',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nutritionalprofile',
            name='bmr',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='nutritionalprofile',
            name='daily_calorie_target',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='nutritionalprofile',
            name='goal',
            field=models.CharField(choices=[('PERDA', 'Perda'), ('MANUTENCAO', 'Manuteção'), ('GANHO', 'Ganho')], default='MANUTENCAO', max_length=15),
        ),
        migrations.AddField(
            model_name='nutritionalprofile',
            name='height_cm',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nutritionalprofile',
            name='remind_interval_hours',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='nutritionalprofile',
            name='sex',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], default='F', max_length=1),
        ),
        migrations.AddField(
            model_name='nutritionalprofile',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='nutritionalprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nutritional_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='weeklyplan',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='weeklyplan',
            name='plan_data',
            field=models.JSONField(),
        ),
    ]
