# Generated by Django 5.2.12 on 2026-04-08 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodRestriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restriction_type', models.CharField(choices=[('CELIACO', 'Celíaco'), ('INTOLERANTE_A_LACTOSE', 'Intolerante à Lactose'), ('DIABETICO', 'Diabético'), ('VEGANO', 'Vegano'), ('VEGETARIANO', 'Vegetariano'), ('OUTRO', 'Outro')], max_length=30)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restrictions', to='profiles.nutritionalprofile')),
            ],
        ),
    ]
