# Generated by Django 5.2.12 on 2026-04-09 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_foodrestriction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodrestriction',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dietary_restrictions', to='profiles.nutritionalprofile'),
        ),
    ]
