# Generated by Django 5.2.13 on 2026-04-22 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_foodrestriction_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritionalprofile',
            name='dietary_restrictions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='foodrestriction',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restriction_items', to='profiles.nutritionalprofile'),
        ),
    ]
