# Generated by Django 5.2.13 on 2026-04-23 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_nutritionalprofile_dietary_restrictions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodrestriction',
            name='restriction_type',
            field=models.CharField(choices=[('CELIACO', 'Celíaco'), ('INTOLERANTE_A_LACTOSE', 'Intolerante à Lactose'), ('DIABETICO', 'Diabético'), ('ALERGICO_OVO', 'Alérgico a ovo'), ('FRUTOS_DO_MAR', 'Alérgico a frutos do mar'), ('AMENDOIM', 'Alérgico a amendoim'), ('SOJA', 'Alérgico à soja'), ('AVEIA', 'Alérgico à aveia'), ('VEGANO', 'Vegano'), ('VEGETARIANO', 'Vegetariano'), ('OUTRO', 'Outro')], max_length=30),
        ),
    ]
