# Generated by Django 5.2.13 on 2026-05-11 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_saveddiet_savedrecipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritionalprofile',
            name='remind_interval_hours',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='foodrestriction',
            name='restriction_type',
            field=models.CharField(choices=[('CELIACO', 'Celíaco'), ('INTOLERANTE_A_LACTOSE', 'Intolerante à Lactose'), ('DIABETICO', 'Diabético'), ('ALERGICO_OVO', 'Alérgico a ovo'), ('FRUTOS_DO_MAR', 'Alérgico a frutos do mar'), ('AMENDOIM', 'Alérgico a amendoim'), ('SOJA', 'Alérgico à soja'), ('AVEIA', 'Alérgico à aveia'), ('OUTRO', 'Outro')], max_length=30),
        ),
    ]
