# Generated by Django 5.2.13 on 2026-05-12 00:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_nutritionalprofile_remind_interval_hours_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Meu Plano Semanal', max_length=255)),
                ('is_active', models.BooleanField(default=False, help_text='É o plano que o usuário está seguindo agora?')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('target_kcal_per_day', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('plan_data', models.JSONField(help_text='JSON estruturado contendo os dias, refeições e ingredientes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_plans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
