# Generated by Django 5.2.13 on 2026-06-30 19:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_weeklyplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritionalprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='weeklyplan',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='weeklyplan',
            name='plan_data',
            field=models.JSONField(),
        ),
    ]
