services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - 8000:8000
    volumes:
      - ./src:/app/src
    environment:
      - PYTHONPATH=/app/src
    env_file:
      - .env
    command: ["python", "src/manage.py", "runserver", "0.0.0.0:8000"]
    depends_on:
      db:
        condition: service_healthy
        restart: true
      redis:
        condition: service_healthy
        restart: true

  ##############################################################################

  celery:
    build:
      context: .
      target: dev
    environment:
      - PYTHONPATH=/app/src
    env_file:
      - .env
    volumes:
      - ./src:/app/src
    depends_on:
      db:
        condition: service_healthy
        restart: true
      redis:
        condition: service_healthy
        restart: true
    command: ["celery", "-A", "core.celery:app", "worker", "--loglevel=info"]

  ##############################################################################

  db:
    image: postgres:18
    volumes:
      - postgres_data:/var/lib/postgresql
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 30s

  ##############################################################################

  redis:
    image: redis:8.2-bookworm
    volumes:
      - redis_data:/data
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  postgres_data:
  redis_data:
