# Generated by Django 5.2.13 on 2026-07-01 23:54

from decimal import Decimal

import django.core.validators
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.RunSQL(
            "CREATE EXTENSION IF NOT EXISTS vector;",
            reverse_sql="DROP EXTENSION IF EXISTS vector;",
        ),
        migrations.CreateModel(
            name="Food",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(
                        blank=True, dimensions=3072, null=True
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("usda", "US Departament of Agriculture"),
                            ("manual", "Manual"),
                            ("off", "Open Food Facts"),
                        ],
                        max_length=10,
                    ),
                ),
                ("outsource_fdc_id", models.IntegerField(blank=True, null=True)),
                (
                    "kcal_per_100g",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "protein_per_100g",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "carbs_per_100g",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "fat_per_100g",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "fiber_per_100g",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("allergens", models.JSONField(blank=True, default=list)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
