# Generated by Django 5.2.12 on 2026-04-19 06:45

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_delete_meallog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='kcal_per_100g',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
