# Generated by Django 5.2.13 on 2026-05-12 01:05

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0005_food_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=3072, null=True),
        ),
    ]
