# Generated by Django 5.2.13 on 2026-07-02 04:27

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealitem',
            name='computed_metrics',
        ),
        migrations.RemoveField(
            model_name='mealitem',
            name='quantity',
        ),
        migrations.AddField(
            model_name='meal',
            name='eaten_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mealitem',
            name='kcal_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='mealitem',
            name='quantity_grams',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.1'))]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to=settings.AUTH_USER_MODEL),
        ),
    ]
