# Generated by Django 5.2.13 on 2026-07-02 03:13

import django.db.models.deletion
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunSQL(
            "CREATE EXTENSION IF NOT EXISTS vector;",
            reverse_sql="DROP EXTENSION IF EXISTS vector;",
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=3072, null=True)),
                ('muscle_group', models.CharField(choices=[('chest', 'Peitoral'), ('back', 'Costas'), ('quads', 'Quadriceps'), ('hamstrings', 'Posteriores'), ('shoulders', 'Ombros'), ('biceps', 'Bíceps'), ('triceps', 'Tríceps'), ('glutes', 'Glúteos'), ('calves', 'Panturrilhas'), ('abs', 'Abdômen')], max_length=50)),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AIWorkoutRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(help_text='Conteúdo em Markdown gerado pela IA')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan_data', models.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FitnessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remind_interval_hours', models.PositiveSmallIntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('experience_level', models.CharField(choices=[('beginner', 'Iniciante'), ('intermediary', 'Intermediário'), ('advanced', 'Avançado')], max_length=20)),
                ('primary_goal', models.CharField(choices=[('hypertrophy', 'Hipertrofia'), ('powerlift', 'Força'), ('weight_loss', 'Perda de Peso')], max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MuscleVolumeGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_value', models.FloatField()),
                ('current_value', models.FloatField(blank=True, null=True)),
                ('metric_unit', models.CharField(max_length=50)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('is_achieved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('muscle_group', models.CharField(choices=[('chest', 'Peitoral'), ('back', 'Costas'), ('quads', 'Quadriceps'), ('hamstrings', 'Posteriores'), ('shoulders', 'Ombros'), ('biceps', 'Bíceps'), ('triceps', 'Tríceps'), ('glutes', 'Glúteos'), ('calves', 'Panturrilhas'), ('abs', 'Abdômen')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('duration_minutes', models.PositiveIntegerField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkoutSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reps', models.PositiveIntegerField()),
                ('weight', models.FloatField(help_text='Peso em Kg')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academia.exercise')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='academia.workoutsession')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
